import fs from 'fs';
let content = fs.readFileSync('server.ts', 'utf-8');

const searchResult = `                 resolvedUpdateText = \`🤖 𝗗𝗘𝗩𝗜𝗟 𝗥𝗔𝗦𝗛𝗘𝗗 𝗔𝗜  [RESULT]\\n━━━━━━━━━━━━━━━━━━━\\n🔖 *Period:* \\\`\${nextPrediction.issue}\\\`\\n🧠 *Prediction:* \${nextPrediction.suggest === 'Big' ? '🟢 BIG' : '🔴 SMALL'}\\n🎯 *Market Out:* \${sizeStr} (\${latestIssue.number}) - \${colorStr}\\n✅ *Status:* *\${statusText}*\\n━━━━━━━━━━━━━━━━━━━\`;`;
const replaceResult = `                 resolvedUpdateText = \`✧⋄⋆⋅⋆⋄✧⋄⋆⋅⋆⋄✧⋄⋆⋅⋆⋄✧\\n👑 𝗗𝗘𝗩𝗜𝗟 𝗥𝗔𝗦𝗛𝗘𝗗 𝗔𝗜 👑\\n        [  𝗥𝗘𝗦𝗨𝗟𝗧  ]\\n✧⋄⋆⋅⋆⋄✧⋄⋆⋅⋆⋄✧⋄⋆⋅⋆⋄✧\\n\\n🔖 𝗣𝗲𝗿𝗶𝗼𝗱: \\\`\${nextPrediction.issue}\\\`\\n🧠 𝗣𝗿𝗲𝗱𝗶𝗰𝘁𝗶𝗼𝗻: \${nextPrediction.suggest === 'Big' ? '🟩 𝗕𝗜𝗚' : '🟥 𝗦𝗠𝗔𝗟𝗟'}\\n🎯 𝗠𝗮𝗿𝗸𝗲𝘁 𝗢𝘂𝘁: \${sizeStr} (\${latestIssue.number}) - \${colorStr}\\n✅ 𝗦𝘁𝗮𝘁𝘂𝘀: *\${statusText}*\\n\\n⚡ 𝗡𝗲𝘂𝗿𝗮𝗹 𝗡𝗲𝘁𝘄𝗼𝗿𝗸 𝗦𝘆𝗻𝗰𝗲𝗱 ✅\\\`;`;

const searchNewMsg = `             const newMsgText = \`👑 *DEVIL RASHED AI ENGINE* 👑\\n━━━━━━━━━━━━━━━━━━━\\n🔖 *Period:* \\\`\${nextPrediction.issue}\\\`\\n🧠 *AI Prediction:*  \${suggestPretty}\\n⚡ *Confidence:*  *\${nextPrediction.confidence}* [\${safeStr}]\\n📊 *Fund:*  Level \${Math.min(globalLossStreak + 1, 6)} Bet\\n━━━━━━━━━━━━━━━━━━━\\n🔎 *Market Out:* Waiting...\\n⌛ *Status:* Pending...\${marketStatusAlert}\`;`;
const replaceNewMsg = `             const newMsgText = \`🔥 𝗔𝗗𝗩𝗔𝗡𝗖𝗘𝗗 𝗔𝗜 𝗘𝗡𝗚𝗜𝗡𝗘 🔥\\n━━━━━━━━━━━━━━━━━━━━\\n🔖 𝗣𝗲𝗿𝗶𝗼𝗱: \\\`\${nextPrediction.issue}\\\`\\n\\n🧠 𝗔𝗜 𝗣𝗿𝗲𝗱𝗶𝗰𝘁𝗶𝗼𝗻: \\n👉 \${suggestPretty} 👈\\n\\n⚡ 𝗔𝗰𝗰𝘂𝗿𝗮𝗰𝘆/𝗖𝗼𝗻𝗳𝗶𝗱𝗲𝗻𝗰𝗲: \${nextPrediction.confidence.includes('%') ? nextPrediction.confidence : nextPrediction.confidence + '%'} [\${safeStr}]\\n📊 𝗙𝘂𝗻𝗱 𝗟𝗲𝘃𝗲𝗹: 𝗟𝘃𝗹 \${Math.min(globalLossStreak + 1, 6)}\\n━━━━━━━━━━━━━━━━━━━━\\n⏳ 𝗪𝗮𝗶𝘁𝗶𝗻𝗴 𝗳𝗼𝗿 𝗿𝗲𝘀𝘂𝗹𝘁...\${marketStatusAlert}\`;`;

const searchTimer = `      const text = \`👑 *DEVIL RASHED AI ENGINE* 👑\\n━━━━━━━━━━━━━━━━━━━\\n🔖 *Period:* \\\`\${nextPrediction.issue}\\\`\\n🧠 *AI Prediction:*  \${suggestPretty}\\n⚡ *Confidence:*  *\${nextPrediction.confidence}*\\n📊 *Fund:*  Level \${Math.min(globalLossStreak + 1, 6)} Bet\\n━━━━━━━━━━━━━━━━━━━\\n🔎 *Market Out:* Waiting...\\n⌛ *Status:* Pending...\\n\\n⏱️ *Next Period:* ~\${remainingSeconds}s\`;`;
const replaceTimer = `      const text = \`🔥 𝗔𝗗𝗩𝗔𝗡𝗖𝗘𝗗 𝗔𝗜 𝗘𝗡𝗚𝗜𝗡𝗘 🔥\\n━━━━━━━━━━━━━━━━━━━━\\n🔖 𝗣𝗲𝗿𝗶𝗼𝗱: \\\`\${nextPrediction.issue}\\\`\\n\\n🧠 𝗔𝗜 𝗣𝗿𝗲𝗱𝗶𝗰𝘁𝗶𝗼𝗻:\\n👉 \${suggestPretty} 👈\\n\\n⚡ 𝗔𝗰𝗰𝘂𝗿𝗮𝗰𝘆/𝗖𝗼𝗻𝗳𝗶𝗱𝗲𝗻𝗰𝗲: \${nextPrediction.confidence.includes('%') ? nextPrediction.confidence : nextPrediction.confidence + '%'} \\n📊 𝗙𝘂𝗻𝗱 𝗟𝗲𝘃𝗲𝗹: 𝗟𝘃𝗹 \${Math.min(globalLossStreak + 1, 6)}\\n━━━━━━━━━━━━━━━━━━━━\\n⏳ 𝗪𝗮𝗶𝘁𝗶𝗻𝗴 𝗳𝗼𝗿 𝗿𝗲𝘀𝘂𝗹𝘁...\\n\\n⏱️ 𝗧𝗶𝗺𝗲 𝗟𝗲𝗳𝘁: \${remainingSeconds}s 🚀\`;`;

if (content.includes(searchResult)) content = content.replace(searchResult, replaceResult);
if (content.includes(searchNewMsg)) content = content.replace(searchNewMsg, replaceNewMsg);
if (content.includes(searchTimer)) content = content.replace(searchTimer, replaceTimer);
fs.writeFileSync('server.ts', content);
console.log("Formatting injected.");
